@extends('admin.layout')

@section('title', $suggestion->exists ? 'Edit Food Trail' : 'Add Food Trail')
@section('page-title', 'Food Trails')

@section('content')
    <style>
        #restaurantOptions { display:grid; grid-template-columns:repeat(auto-fit,minmax(260px,1fr)); gap:10px; max-height:460px; overflow:auto; padding:4px; align-items:stretch; }
        .restaurant-option { width:100%; min-height:112px; text-align:left; padding:14px !important; border:1px solid #ead9c3 !important; border-radius:16px !important; background:#fffdf9 !important; }
        .restaurant-option:hover { border-color:#b8874a !important; background:#fff7eb !important; }
        .restaurant-option strong { display:block; color:#30251f; font-size:15px; }
        .restaurant-option small { display:block; margin-top:5px; color:#78695d; line-height:1.35; }
        .restaurant-option small:last-child { display:-webkit-box; -webkit-line-clamp:2; -webkit-box-orient:vertical; overflow:hidden; }
        /* Override the shared .button flex layout for readable result cards. */
        .button.restaurant-option { display:block !important; height:auto; min-height:142px !important; overflow:hidden; padding:18px !important; }
        .restaurant-option strong { display:block; min-height:0; margin-bottom:8px; padding-right:96px; position:relative; line-height:1.3; }
        .restaurant-option strong span { position:absolute; right:0; top:0; padding:5px 9px; border:1px solid #d8b58f; border-radius:999px; background:white; }
        #selectedRestaurants li { display:flex; flex-direction:column; gap:7px; padding:16px !important; }
        #selectedRestaurants .remove-stop { align-self:flex-start; margin-top:6px; border:1px solid #c85b4a; border-radius:999px; background:#fff; color:#b54434; padding:7px 12px; font-weight:700; }
    </style>
    <div class="page-header"><div><p class="eyebrow">User recommendations</p><h1>{{ $suggestion->exists ? 'Edit suggestion' : 'Add suggestion' }}</h1><p>Users will see published suggestions in Food Trails.</p></div></div>
    @if ($errors->any())<div class="status-banner error"><strong>Please correct the highlighted details.</strong><ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form class="panel" method="POST" action="{{ $suggestion->exists ? route('admin.food-trails.update', $suggestion) : route('admin.food-trails.store') }}">
        @csrf @if($suggestion->exists) @method('PUT') @endif
        <div class="field"><label for="title">Trail title</label><input id="title" name="title" value="{{ old('title', $suggestion->title) }}" required></div>
        <div class="field" style="margin-top:16px"><label for="subtitle">Short description</label><input id="subtitle" name="subtitle" value="{{ old('subtitle', $suggestion->subtitle) }}"></div>
        <div class="field" style="margin-top:16px"><label for="summary">Recommendation details</label><textarea id="summary" name="summary" required>{{ old('summary', $suggestion->summary) }}</textarea></div>
        <div class="filters" style="margin-top:16px"><div class="field"><label for="location">Location</label><select id="location" name="location">@foreach($locations as $location)<option value="{{ $location }}" @selected(old('location', $suggestion->location) === $location)>{{ $location }}</option>@endforeach</select></div><div class="field"><label for="category">Category</label><select id="category" name="category">@foreach($categories as $category)<option value="{{ $category }}" @selected(old('category', $suggestion->category ?: 'All') === $category)>{{ $category }}</option>@endforeach</select></div></div>
        <div class="field" style="margin-top:16px"><label><input type="hidden" name="is_published" value="0"><input type="checkbox" name="is_published" value="1" @checked(old('is_published', $suggestion->exists ? $suggestion->is_published : true))> Show this suggestion to users</label></div>
        @php($selected = old('restaurant_ids', $suggestion->restaurants->pluck('id')->all()))
        <div class="field" style="margin-top:16px"><label>Restaurants (search and add; drag to reorder)</label><input id="restaurantSearch" placeholder="Search by restaurant, category, or location" style="margin:8px 0"><div id="restaurantOptions">@foreach($restaurants as $restaurant)<button type="button" class="button secondary small restaurant-option" data-id="{{ $restaurant->id }}" data-name="{{ $restaurant->shop_name }}" data-meta="{{ $restaurant->primary_food_category ?: 'Heritage food' }} · {{ $restaurant->address ?: $restaurant->city ?: 'Location not listed' }}" data-description="{{ $restaurant->heritage_story ?: $restaurant->highlight ?: 'No shop description available.' }}"><strong>{{ $restaurant->shop_name }} <span style="float:right;color:#b8874a">+ Add</span></strong><small>{{ $restaurant->primary_food_category ?: 'Heritage food' }} · {{ $restaurant->address ?: $restaurant->city ?: 'Location not listed' }}</small><small>{{ $restaurant->heritage_story ?: $restaurant->highlight ?: 'No shop description available.' }}</small></button> @endforeach</div><ol id="selectedRestaurants" style="margin-top:12px">@foreach($selected as $id) @php($restaurant = $restaurants->firstWhere('id', $id)) @if($restaurant)<li draggable="true" data-id="{{ $id }}" style="margin:8px 0;padding:10px;border:1px solid #e9d7bf;border-radius:12px;cursor:grab"><strong>☰ {{ $restaurant->shop_name }}</strong><br><small>{{ $restaurant->primary_food_category ?: 'Heritage food' }} · {{ $restaurant->address ?: $restaurant->city ?: 'Location not listed' }}</small><br><small>{{ $restaurant->heritage_story ?: $restaurant->highlight ?: 'No shop description available.' }}</small> <button type="button" class="remove-stop">Remove</button><input type="hidden" name="restaurant_ids[]" value="{{ $id }}"></li>@endif @endforeach</ol></div>
        <div class="actions"><button class="button primary">{{ $suggestion->exists ? 'Save changes' : 'Add suggestion' }}</button><a class="button secondary" href="{{ route('admin.food-trails.index') }}">Cancel</a></div>
    </form>
    <script>const list=document.getElementById('selectedRestaurants'),search=document.getElementById('restaurantSearch');document.querySelectorAll('.restaurant-option').forEach(b=>b.onclick=()=>{if(list.querySelector(`[data-id="${b.dataset.id}"]`))return;list.insertAdjacentHTML('beforeend',`<li draggable="true" data-id="${b.dataset.id}" style="margin:8px 0;padding:10px;border:1px solid #e9d7bf;border-radius:12px;cursor:grab"><strong>☰ ${b.dataset.name}</strong><br><small>${b.dataset.meta}</small><br><small>${b.dataset.description}</small> <button type="button" class="remove-stop">Remove</button><input type="hidden" name="restaurant_ids[]" value="${b.dataset.id}"></li>`)});search.oninput=()=>document.querySelectorAll('.restaurant-option').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(search.value.toLowerCase())?'':'none');list.onclick=e=>{if(e.target.classList.contains('remove-stop'))e.target.closest('li').remove()};let drag;list.ondragstart=e=>drag=e.target.closest('li');list.ondragover=e=>e.preventDefault();list.ondrop=e=>{e.preventDefault();const target=e.target.closest('li');if(target&&drag!==target)list.insertBefore(drag,target)};</script>
@endsection
